### ISSUE TITLE
Template Strings for CSS, JAVASCRIPT problem

### ISSUE THREAD

**Issue by pcktlwyrcode** [PacktPublishing/Rust-Web-Programming#10]
FOR {{BASE_CSS}} in main.html:
I get errors
at-rule or selector expected
{ expected
at-rule or selector expected

----------------------------------
{{JAVASCRIPT}}
console
reference error JAVASCRIPT not defined

**Comment by maxwellflitton** [comment]
Hey @pcktlwyrcode thanks for the comment, do you have the chapter number and file/dectory where this is happening? Many thanks maxwell

**Comment by pcktlwyrcode** [comment]
Hi Maxwell,


I have had the same issue with both the Javascript and CSS template tags.
Chapter 5 Displaying Content in the Browser, Injecting Javascript and
Injecting CSS into HTML.

**Comment by maxwellflitton** [comment]
Hey @pcktlwyrcode 

I've just downloaded this repo again and ran the injecting JavaScript and injecting CSS. I am not getting any issues, it seems to be running fine. Can you give me a stack trace so I can see if I can help you as I cannot recreate the issue myself.

**Comment by pcktlwyrcode** [comment]
Dear Maxwell,

Thanks for getting back to me.
Indeed.
I managed to get the problem resolved by running the code again this
morning.
The problem seems to be with one of the Rust tools I am using in VS Code.
I really hope you write a second book perhaps with more advanced topics in
Rust.
This one is very well written (concise, ie none of the repetition one
normally sees) in a very interesting area.

Regards,

Pcktlwyr

**Comment by pcktlwyrcode** [comment]
Problem was at with Rust tools in VS Code. Managed to compile and run as expected.

**Comment by maxwellflitton** [comment]
@pcktlwyrcode no worries thanks for bringing this to our attention. Right now I'm writing a book on fusing Rust with Python so developers can write entire pip modules in Rust that Python can import and use. I appreciate you reading the book and I hope you're enjoying it.
