### ISSUE TITLE
Ch10_deploy locally

### ISSUE THREAD

**Issue by AHSPONTES** [PacktPublishing/Rust-Web-Programming#11]
Hey Max,

You did really a great job writing this book. Thank you.

I hope you can give me some advice about an error I am getting here.

On chapter 10 (p.275) after I tried to create an user I got the followed error:
"502 Bad Gateway"

I am still trying to resolve. Could you help me with that?

Thank you

**Comment by AHSPONTES** [comment]
So bro, I kept trying to find what was going on.
So I compared our codes.
The difference was on:
main.rs
 I changed the IP from the bind fn from "127.0.0.1:8000"  to "0.0.0.0:8000"
Cargo.toml
I added the crate openssl = "*"

What do you think about the problem?

Thank you for writing the book again. I am having a really good experience.

**Comment by AHSPONTES** [comment]
So bro, I kept trying to find what was going on.
So I compared our codes.
The difference was on:
main.rs
 I changed the IP from the bind fn from "127.0.0.1:8000"  to "0.0.0.0:8000"
Cargo.toml
I added the crate openssl = "*"

What do you think about the problem?

Thank you for writing the book again. I am having a really good experience.

**Comment by maxwellflitton** [comment]
@AHSPONTES LOL just ran the code and you've literally beaten me by 2 minutes, I pulled the chapter 10 running locally and it worked with the outcome below:
<img width="1429" alt="Screenshot 2021-07-29 at 02 47 36" src="https://user-images.githubusercontent.com/17654010/127419312-002e3860-61d9-43dd-94a5-51701e6f8b77.png">

I'm glad you're enjoying it as I love Rust. I also checked out your github and it's really cool that you're working through the book and uploading the code on a repo. I am excited to see what you will do with it and will be working on a second edition over the next couple of years. If you have any questions in general about web development in Rust that is not specific to the book feel free to email me at maxwellflitton@gmail.com. I will take what you've done into account, leafing through the book I don't think that I highlighted these steps, I hope it didn't take up too much of your time. I will contact the publishers for adding this change to future editions. Thank you for taking the time to write your problem, I appreciate it.

**Comment by maxwellflitton** [comment]
@AHSPONTES again thanks for the comments. I'm working on the second edition of the Rust web programming book. There are some improvements/updates on the JWT and database connections. I've also included a ReactJS front-end for the to-do application here is the code repo: https://github.com/PacktPublishing/Rust-for-Web-Developers

**Comment by 0xpontes** [comment]
Awesome! 
Let me know when you launch it.
I am keen to read it =)
