### ISSUE TITLE
Ch1 struct

### ISSUE THREAD

**Issue by samusz** [PacktPublishing/Rust-Web-Programming#14]
Hi, 
creating the files along my reading of the book (just begun), for it to compile, I had to do : 
`
 struct Human {
     name: String,
      age: i8,
      current_thought: String
  }
 
  impl Human {-
      fn new (name: &str, age: i8) -> Human {
          return Human {
              name: name.to_string(),
              age,
              current_thought: String::from("nothing")
        }
      }
 
     fn with_thought (mut self, thought: &str ) -> Human {
          self.current_thought  = thought.to_string();
          return self
      }
 
      fn speak (&self) -> () {
          println! ("Hello my name is {} and I'm {} years old.",
                    &self.name,
                    &self.age);
      }
  }
 
 
  fn main() {
      let developper = Human::new("Grace", 30)
          .with_thought("Let's code !");
      developper.speak();
      println!("Hello, world!");
  }
`

I've  seen that the code in the repo here is changed from the book's, so I gess this issue is mainly solved with Strings in the repo.

As I've solved it keeping the &str, I just wanted to document another way to fix it. 
Best

Sacha

**Comment by maxwellflitton** [comment]
Hey @samusz thank you for adding this. Hope the book reading is going well. I have checked and it's interesting that we are working in similar fields. I'm currently working for OasisLMF for open source weather disaster modelling. Would love to hear what you use the book for.
