### ISSUE TITLE
In case anyone runs into a problem getting diesel_cli to install in Chapter 6

### ISSUE THREAD

**Issue by jasonsalas** [PacktPublishing/Rust-Web-Programming#15]
I'm working through the excellent tutorials, but I hit a snag when trying to install _diesel_cli_, in order to connect to PostgreSQL via Docker. The catch is that you need the DB libraries installed locally. I'm on Windows 10 using Ubuntu via WSL, so I kept getting errors, until I ran:

**sudo apt install libpq-dev**

Everything works after that!

**Comment by shruthis-shetty** [comment]
> I'm working through the excellent tutorials, but I hit a snag when trying to install _diesel_cli_, in order to connect to PostgreSQL via Docker. The catch is that you need the DB libraries installed locally. I'm on Windows 10 using Ubuntu via WSL, so I kept getting errors, until I ran:
> 
> **sudo apt install libpq-dev**
> 
> Everything works after that!

Hey @jasonsalas , do you need any help/ it is sorted now?

Please give us the updates here.

**Comment by jasonsalas** [comment]
Oh yeah, it's all better after installing the additional package, Thanks!
